name: SonarQube Analysis

on:
  push:
    branches:
      - develop

jobs:
  sonar:
    runs-on:  self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SonarScanner
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
        unzip sonar-scanner-cli-4.8.0.2856-linux.zip
        rm -rf ~/.sonar-scanner
        mv sonar-scanner-4.8.0.2856-linux ~/.sonar-scanner

    - name: Fix sh Symlink
      run: sudo ln -sf /bin/bash /bin/sh

    - name: Debug PATH and Shell
      run: |
        echo "Current PATH: $PATH"
        which sh || echo "sh not found in PATH"
        which bash || echo "bash not found in PATH"
        ~/.sonar-scanner/bin/sonar-scanner --version

    - name: Run SonarQube Analysis
      shell: sh
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
        PATH: /usr/lib/jvm/java-11-openjdk-amd64/bin:$PATH:~/.sonar-scanner/bin
      run: |
        ~/.sonar-scanner/bin/sonar-scanner \
        -Dsonar.projectKey=Authentication \
        -Dsonar.sources=. \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN
